version: '3.2'
services:
  db:
    image: postgres
  app:
    build: .
    command: rails server
    env_file:
      .env
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
    stdin_open: true
    tty: true
