version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: commands/app
    env_file:
      .env
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
