version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        rails server -b '0.0.0.0' -p 3000
      "
    env_file:
      .env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
